Insert Into Station VALUES('Hyderbad', 'Telangana')
Insert Into Station VALUES('Warangal', 'Telangana')
Insert Into Station VALUES('Karim Nagar', 'Telangana')
Insert Into Station VALUES('Nizambad', 'Telangana')
Insert Into Station VALUES('Khammam', 'Telangana')
